services:
- docker

before_install:
- docker pull tfoote/planet-venus

script:
- docker run -v `pwd`:/planet tfoote/planet-venus planet /planet --verbose /planet/planet.ini

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: output
  on:
    branch: gh-pages