services:
- docker

script:
- ./build.bash
- echo 'planet.ros.org'  | sudo tee output/CNAME

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: false
  local_dir: output
  on:
    branch: master  # only deploy from master
  target_branch: gh-pages
