services:
- docker

script:
- ./build.bash

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: output
  on:
    branch: master  # only deploy from master
  target_branch: gh-pages